spring:
  application:
    name: url-shortner

  # MySQL Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/url_shortner?useSSL=false&serverTimezone=UTC
    username: sud
    password: sud@123
    # driver-class-name: com.mysql.cj.jdbc.Driver  # Optional, usually not needed

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      # password: your_redis_password